from tkinter import *
from tkinter import ttk
from tkinter.ttk import Treeview
import tkinter.font
import linksql
import warning

 
class Operation(object):
    def __init__(self,idd,master=None):
        self.root=master
        self.idd=idd
        self.root.title("                                                                                                                                    用户登录界面")
        self.root.geometry('970x620+200+100')
        self.root.resizable(False,False)
        self.createPage()
    def createPage(self):
        self.win=Frame(self.root,width=970,height=620)
        self.win.place(x=0,y=0)
        self.ft=tkinter.font.Font(family='Fixdsys',size=12,weight='bold')
        self.cv=Canvas(self.win,width=800,height=750)
        self.cv1=Canvas(self.win,bg="skyblue",width=120,height=605)
        self.cv1.place(x=2,y=3)
        self.cv2=Canvas(self.win,bg="gray",width=820,height=605)
        self.cv2.place(x=130,y=3)
        self.btn1=Button(self.win,text="个人资料",font=self.ft,width=10,height=2,command=self.view_interface)
        self.btn1.place(x=11,y=80)
        self.btn5=Button(self.win,text='修改信息',font=self.ft,width=10,height=2,command=self.update_self_news)
        self.btn5.place(x=11,y=180)
        self.btn2=Button(self.win,text="医院风采",font=self.ft,width=10,height=2)
        self.btn2.place(x=11,y=280)
        self.btn3=Button(self.win,text="医学文库",font=self.ft,width=10,height=2)
        self.btn3.place(x=11,y=380)
        self.btn4=Button(self.win,text="生活常识",font=self.ft,width=10,height=2)
        self.btn4.place(x=11,y=480)
    def view_interface(self):                          #用户查看界面
        ft=tkinter.font.Font(family='方正粗黑宋简',size=23,weight='bold')
        cv=Canvas(self.win,bg="gray",width=820,height=605)
        cv.place(x=130,y=3)
        cv1=Canvas(self.win,bg="gray",width=810,height=50)
        cv1.place(x=135,y=8)
        lab1=Label(cv1,text='  W   e   l   c   o   m   e !',fg='yellow',font=ft,bg='gray')
        lab1.place(x=130,y=15)
        cv1=Canvas(self.win,bg="pink",width=810,height=540)
        cv1.place(x=135,y=61)
        frame = Frame(cv1)
        frame.place(x=5, y=8, width=804, height=530)
        scrollBar = Scrollbar(frame)
        scrollBar.pack(side=RIGHT, fill=Y)
        tree = Treeview(frame,columns=('c1', 'c2', 'c3','c4', 'c5', 'c6','c7','c8'),show="headings",yscrollcommand=scrollBar.set)
        tree.column('c1', width=150, anchor='center')
        tree.column('c2', width=105, anchor='center')
        tree.column('c3', width=70, anchor='center')
        tree.column('c4', width=70, anchor='center')
        tree.column('c5', width=90, anchor='center')
        tree.column('c6', width=105, anchor='center')
        tree.column('c7', width=105, anchor='center')
        tree.column('c8', width=90, anchor='center')
        tree.heading('c1', text='ID')
        tree.heading('c2', text='姓名')
        tree.heading('c3', text='性别')
        tree.heading('c4', text='年龄')
        tree.heading('c5', text='类别')
        tree.heading('c6', text='电话')
        tree.heading('c7', text='科室')
        tree.heading('c8', text='主治医生')
        tree.pack(side=LEFT, fill=Y)
        scrollBar.config(command=tree.yview)
        result=linksql.SQL().search_one_patient2(self.idd)
        tree.insert('',0,values=(result[0][0],result[0][1],result[0][2],result[0][3],result[0][4],result[0][5],result[0][6],result[0][7]))
    def update_self_news(self):
        cv=Canvas(self.win,bg="gray",width=820,height=605)
        cv.place(x=130,y=3)
        cv1=Canvas(self.win,bg="gray",width=810,height=50)
        cv1.place(x=135,y=8)
        cv1=Canvas(self.win,bg="pink",width=810,height=540)
        cv1.place(x=135,y=61)
        frame = Frame(cv1,bg='white')
        frame.place(x=5, y=5, width=804, height=530)
        bm_right=PhotoImage(file='D:\\pyword\\img\\right.png')
        bm_left=PhotoImage(file='D:\\pyword\\img\\left.png')
        lab_left=Label(frame,image=bm_left,width=220)
        lab_left.bm=bm_left
        lab_left.place(x=0,y=0)
        lab_right=Label(frame,image=bm_right,width=220)
        lab_right.bm=bm_right
        lab_right.place(x=560,y=0)
        frame_fresh = Frame(frame,bg='gray')
        frame_fresh.place(x=240, y=5, width=310, height=500)
        lab1=Label(frame_fresh,text='个人修改界面',bg='gray')
        lab1.place(x=115,y=20)
        lab2=Label(frame_fresh,text='用户名',bg='gray',width=10)
        lab2.place(x=2,y=70)
        lab2=Label(frame_fresh,text='密  码',bg='gray',width=10)
        lab2.place(x=2,y=120)
        self.try30=StringVar()
        self.try31=StringVar()
        self.entry30=Entry(frame_fresh,textvariable=self.try30,width=27)
        self.entry30.place(x=90,y=70)
        self.entry31=Entry(frame_fresh,textvariable=self.try31,width=27)
        self.entry31.place(x=90,y=120)
        btn1=Button(frame_fresh,text='确   定',width=10,command=self.update_success3)
        btn1.place(x=120,y=430) 
    def update_success3(self):
        a21=self.entry30.get()
        a22=self.entry31.get()
        if len(a21)!=0:
            linksql.SQL().update_patient_username(a21,self.idd)
        elif len(a22)!=0:
            linksql.SQL().update_patient_passwd(a22,self.idd)
    def hos_hy(self):
        ft = tkinter.font.Font(family='方正粗黑宋简', size=23, weight='bold')
        cv = Canvas(self.win, bg="gray", width=820, height=605)
        cv.place(x=130, y=3)
        cv1 = Canvas(self.win, bg="gray", width=810, height=50)
        cv1.place(x=135, y=8)
        lab1 = Label(cv1, text='  W   e   l   c   o   m   e !', fg='yellow', font=ft, bg='gray')
        lab1.place(x=130, y=15)
        cv1 = Canvas(self.win, bg="pink", width=810, height=540)
        cv1.place(x=135, y=61)
        frame = Frame(cv1)
        frame.place(x=5, y=8, width=804, height=530)
        scrollBar = Scrollbar(frame)
        scrollBar.pack(side=RIGHT, fill=Y)